-- CREATE DATABASE [$(DB_NAME)];
-- ALTER DATABASE [$(DB_NAME)]
--     SET RECOVERY FULL;


-- BACKUP DATABASE [$(DB_NAME)]
--     TO DISK = N'/var/opt/mssql/data/$(DB_NAME).bak';


ALTER AVAILABILITY GROUP [$(AG_NAME)] ADD DATABASE [$(DB_NAME)];