CREATE AVAILABILITY GROUP [$(AG_NAME)]]
    WITH (CLUSTER_TYPE = NONE)
    FOR REPLICA ON
        N'$(NODE1)' WITH (
            ENDPOINT_URL = N'tcp://$(NODE1):5022',
            AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT,
            FAILOVER_MODE = MANUAL,
            SEEDING_MODE = AUTOMATIC,
                    SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL)
        ),
        N'$(NODE2)' WITH (
            ENDPOINT_URL = N'tcp://$(NODE2):5022',
            AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT,
            FAILOVER_MODE = MANUAL,
            SEEDING_MODE = AUTOMATIC,
            SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL)
        );

ALTER AVAILABILITY GROUP [$(AG_NAME)] GRANT CREATE ANY DATABASE;